### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mohamed82008** [ds4dm/Tulip.jl#125]
I am getting version conflicts trying to have the latest NOMAD and latest Percival on one environment. NOMAD requires Tulip 0.9.3 which only supports Krylov 0.7 and Percival requires Krylov 0.8. I see master has been updated a while ago so a new release is probably due?

**Comment by mtanneau** [comment]
Thanks for reporting this. A release is due, yes :)
ETA: this weekend
