### ISSUE TITLE
MPS Reader

### ISSUE THREAD

**Issue by odow** [ds4dm/Tulip.jl#3]
I see you've implemented an MPS reader. I have a writer, but I haven't implemented the reader yet:
https://github.com/odow/MPSWriter.jl/blob/master/src/MPSWriter.jl

I also have a reader/writer for LP files:
https://github.com/odow/LPWriter.jl

**Comment by mtanneau** [comment]
Yes, I only wrote a (dirty) reader so I could import netlib instances.

This is not my top priority right now, but hopefully I'll eventually clean that up and open a PR to add the reader to your MPSWriter.jl

**Comment by odow** [comment]
Just leaving a breadcrumb to https://github.com/odow/MathOptFormat.jl/blob/master/src/MPS/MPS.jl.
Once you implement an interface to MOI, you'll also get an MPS reader/writer :)

**Comment by mtanneau** [comment]
Closing this now that MOF got merged into MOI.
