### ISSUE TITLE
API for parameters

### ISSUE THREAD

**Issue by ericphanson** [ds4dm/Tulip.jl#41]
Very happy to see the BigFloat stuff is working!

I'm planning on making a discourse post announcing Convex.jl 0.13 which supports high-precision problem formulation and MOI. I wanted to show an example with Tulip.jl, and was thinking about adopting the bounded one from `examples.jl`: 

```julia
using Convex, Tulip, Test
x1 = Variable()
x2 = Variable()
constraints = [ x1 + x2 == big(1.0), x1 - x2 == big(0.0), 0 <= x1, 0 <= x2, x1 <= 1, x2 <= 1]
problem = minimize( x1 + 2*x2, constraints; numeric_type = BigFloat)
opt = Tulip.Optimizer{BigFloat}()
opt.inner.env.barrier_tol_pfeas = big(1e-30)
opt.inner.env.barrier_tol_dfeas = big(1e-30)
opt.inner.env.barrier_tol_conv = big(1e-30)
opt.inner.env.barrier_tol_infeas = big(1e-30)
solve!(problem, opt)
@test problem.optval ≈ 1.5 atol=1e-30
```

Is there a better way to set the parameters than I did here?

(the example requires Convex.jl master until 0.13 is tagged).

**Comment by mtanneau** [comment]
>  I wanted to show an example with Tulip.jl

:)

> Is there a better way to set the parameters than I did here?

Not really. The ugly truth is that I never took the time to write a proper API for this.

For tolerances, I generally use `sqrt(eps(Tv))` where `Tv` is the numerical precision type (TBH I thought this was the default, turns out it is not). So for `BigFloat`, you can do something like
```julia
opt.inner.env.barrier_tol_pfeas = sqrt(eps(BigFloat))
opt.inner.env.barrier_tol_dfeas = sqrt(eps(BigFloat))
opt.inner.env.barrier_tol_conv = sqrt(eps(BigFloat))
opt.inner.env.barrier_tol_infeas = sqrt(eps(BigFloat))
```
Note that these are relative tolerances, not absolute. So if your right-hand side (resp objective) has very large coefficients, you might get high primal (res. dual) absolute residual.

**Comment by mtanneau** [comment]
If you want to solve to really high precision and you're using `BigFloat`, you should use the `setprecision` method, which will automatically affect the result of `eps(BigFloat)`.

There's a part of the algorithm where I regularize everything with `sqrt(eps(Tv))`, so if you use BigFloat and set tolerances to, say, `1e-300`, the algorithm will get stuck.

**Comment by ericphanson** [comment]
Any chance you could make those values the default and tag a release? It would make my example nice and clean :).

Thanks for the info about `setprecision`; I've been using that for some examples with [SDPAFamily.jl](https://github.com/ericphanson/SDPAFamily.jl) as well.

**Comment by mtanneau** [comment]
I will try to find the 15min in the coming days
